### PR TITLE
Ices hcr fix

### PR DESCRIPTION
**Pull request by marchtaylor**
Hello,

I'm requesting a pull for the following changes to the `IcesHCR()` function. 

I noticed that the function incorrectly uses the SSB from assessment_year-1, rather than assessment_year+1. Since the function already included a short-term forecast with the intermediate year assumption (using `fwd()`), it was relatively easy to call the HCR again with the new SSB projected for the advice year. Using this new `Ftg`, the `fwd_control` is updated and second short-term forecast is done to determine the TAC in the advice year (see L155-167, and L180-192).

Cheers, Marc

### CODE REVIEW

**Comment by dorleta** [comment]
Hi Marc,

I hope this email finds you well,

Finally, I've some time to work on FLBEIA code.

One question before accepting your changes, are you sure the SSB is assessment_year+1 instead of assessment_year-1. I can find arguments to use one or the other, but I don't know where to find the precise ICES formulation,

Thanks for helping us improving the tool,

Cheers,

Dorleta





De: Marc Taylor ***@***.***>
Enviado el: viernes, 21 de mayo de 2021 12:10
Para: flr/FLBEIA ***@***.***>
CC: Subscribed ***@***.***>
Asunto: [flr/FLBEIA] Ices hcr fix (#55)


Hello,

I'm requesting a pull for the following changes to the IcesHCR() function.

I noticed that the function incorrectly uses the SSB from assessment_year-1, rather than assessment_year+1. Since the function already included a short-term forecast with the intermediate year assumption (using fwd()), it was relatively easy to call the HCR again with the new SSB projected for the advice year. Using this new Ftg, the fwd_control is updated and second short-term forecast is done to determine the TAC in the advice year (see L155-167, and L180-192).

Cheers, Marc

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/flr/FLBEIA/pull/55<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fflr%2FFLBEIA%2Fpull%2F55&data=04%7C01%7Cdgarcia%40azti.es%7C92d3ef54c5db4a0340e508d91c409d1d%7C6219f1193e794e7facdea5750808cd9b%7C0%7C0%7C637571886165580339%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=VOSU4LQDSpphO5SvVkIKW9QCJX1YxrxVSG%2BA1pn2dS8%3D&reserved=0>

Commit Summary

  *   fix to icesHCR
  *   fix to icesHCR
  *   Merge branch 'icesHCR_fix' of github.com:marchtaylor/FLBEIA into icesHCR_fix
  *   sm change

File Changes

  *   M R/MP_3c_HCR_ICES_MSY.R<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fflr%2FFLBEIA%2Fpull%2F55%2Ffiles%23diff-3a927ed87e635985fb15e5f767c54ff0704ab9604f92bbee49eab04f972c8058&data=04%7C01%7Cdgarcia%40azti.es%7C92d3ef54c5db4a0340e508d91c409d1d%7C6219f1193e794e7facdea5750808cd9b%7C0%7C0%7C637571886165580339%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=fjeLCJSogXLpCHEECfa7P1fXR95eVJZK2nsVNDQOCM4%3D&reserved=0> (198)

Patch Links:

  *   https://github.com/flr/FLBEIA/pull/55.patch<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fflr%2FFLBEIA%2Fpull%2F55.patch&data=04%7C01%7Cdgarcia%40azti.es%7C92d3ef54c5db4a0340e508d91c409d1d%7C6219f1193e794e7facdea5750808cd9b%7C0%7C0%7C637571886165590295%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2B6c3C8S3ZbPAIG%2FsPNGUocTOA0dpmJnhxYay8CVn5X8%3D&reserved=0>
  *   https://github.com/flr/FLBEIA/pull/55.diff<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fflr%2FFLBEIA%2Fpull%2F55.diff&data=04%7C01%7Cdgarcia%40azti.es%7C92d3ef54c5db4a0340e508d91c409d1d%7C6219f1193e794e7facdea5750808cd9b%7C0%7C0%7C637571886165590295%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=3Nn%2BSY%2BKkpH7qtWzpzO7yvhqeczk59CC1wga%2FhaZ5jU%3D&reserved=0>

-

**Comment by marchtaylor** [comment]
Hi Dorleta,
This is simply what the ICES HCR rule does in practice. It looks at the SSB that is projected for the advice year (assessment_year+1) (with some assumption for what is happening in the intermediate / assessment year; e.g. status quo F), and computes the advice F based on the SSB at the beginning of the advice year. The HCR was previously basing the TAC on the SSB assessed two years back, which could result in a substantial lag between the stock state at the advice.
Cheers,
Marc

**Comment by marchtaylor** [comment]
I would also mention that if the HCR is using the SSB from the assessment year -1, then there would be no reason to run stf(). The information on the stock size would only be taken from the assessed years.

**Comment by marchtaylor** [comment]
Yes, but you have defined your target F (Ftg) based on the SSB in the assessment year -1:

```
if(ageStruct){
  b.datyr <- ssb(stk)[,year-1,drop = TRUE] # [it]
}else{
  b.datyr <- (stk@stock.n*stk@stock.wt)[,year-1,drop = TRUE] # [it]
}

# Find where the SSB (Age structured) OR Biomass (Aggregated) in relation to reference points.
b.pos <- apply(matrix(1:iter,1,iter),2, function(i) findInterval(b.datyr[i], ref.pts[c('Blim', 'Btrigger'),i]))
Ftg <- ifelse(b.pos == 0, 0, ifelse(b.pos == 1, ref.pts['Fmsy',]*b.datyr/ref.pts[ 'Btrigger',], ref.pts['Fmsy',]))
```

This is not a problem if we are only trying to find out the SSB at the beginning of assessment year +1. Once we have this, we can figure out the Ftg based on that SSB, which is why I believe you need to run the stf a second time.

**Comment by dorleta** [comment]
Hi,

I've made the changes suggested by Marc, sliglthly differently, but with the same result,

I close the request

Thanks Marc,

**Pull request closed without merging**
